src/Entity/Employes.php
<?php

namespace App\Entity;

use DateInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\EmployesRepository;
use DateTime;
use DateTimeInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EmployesRepository::class)]
class Employes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $_id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Ce champ ne peut pas être vide")]
    private ?string $_prenom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Ce champ ne peut pas être vide")]
    private ?string $_nom = null;
    
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Ce champ ne peut pas être vide")]
    private ?string $_telephone = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Ce champ ne peut pas être vide")]
    private ?string $_email = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Ce champ ne peut pas être vide")]
    private ?string $_adresse = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Ce champ ne peut pas être vide")]
    private ?string $_poste = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"Ce champ ne peut pas être vide")]
    private ?int $_salaire = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    #[Assert\NotBlank(message:"Ce champ ne peut pas être vide")]
    private ?DateTimeInterface $_datenaissance = null;

    public function getId(): ?int
    {
        return $this->_id;
    }

    public function getPrenom(): ?string
    {
        return $this->_prenom;
    }

    public function setPrenom(string $_prenom): self
    {
        $this->_prenom = $_prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->_nom;
    }

    public function setNom(string $_nom): self
    {
        $this->_nom = $_nom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->_telephone;
    }

    public function setTelephone(string $_telephone): self
    {
        $this->_telephone = $_telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->_email;
    }

    public function setEmail(string $_email): self
    {
        $this->_email = $_email;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->_adresse;
    }

    public function setAdresse(string $_adresse): self
    {
        $this->_adresse = $_adresse;

        return $this;
    }

    public function getPoste(): ?string
    {
        return $this->_poste;
    }

    public function setPoste(string $_poste): self
    {
        $this->_poste = $_poste;

        return $this;
    }

    public function getSalaire(): ?int
    {
        return $this->_salaire;
    }

    public function setSalaire(int $_salaire): self
    {
        $this->_salaire = $_salaire;

        return $this;
    }

    public function getDatenaissance(): ?\DateTimeInterface
    {
        return $this->_datenaissance;
    }

    public function setDatenaissance(\DateTimeInterface $_datenaissance): self
    {
        $this->_datenaissance = $_datenaissance;

        return $this;
    }
}

src/Form/EmployesType.php
<?php

namespace App\Form;

use App\Entity\Employes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmployesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('_prenom')
            ->add('_nom')
            ->add('_telephone')
            ->add('_email')
            ->add('_adresse')
            ->add('_poste')
            ->add('_salaire')
            ->add('_datenaissance')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employes::class,
        ]);
    }
}

src/Controller/ProjetController.php
<?php

namespace App\Controller;

use App\Entity\Employes;
use App\Form\EmployesType;
use App\Repository\EmployesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProjetController extends AbstractController
{
    #[Route('/', name: 'employe_liste')]
    #[Route("/edit/{id}", name: "employe_edit")]
    public function form(EmployesRepository $repo, Request $globals, EntityManagerInterface $manager, Employes $employe = null)
    {
        $employes = $repo->findAll();
        
        if($employe == null)
        {
            $employe = new Employes;
        }
        $form = $this->createForm(EmployesType::class, $employe);

        $form->handleRequest($globals);

        if($form->isSubmitted() && $form->isValid())
        {
            $manager->persist($employe);
            $manager->flush();

            return $this->redirectToRoute("employe_liste",[
                'id' => $employe->getId()
            ]);
        }
        return $this->renderForm("projet/index.html.twig",[
            'employes' => $employes,
            'form' => $form,
            'editMode' => $employe->getId() !== null
        ]);
    }

    #[Route("/delete/{id}", name:"employe_delete")]
    public function delete(EntityManagerInterface $manager, Employes $employe)
    {
        $manager->remove($employe);
        $manager->flush();

        return $this->redirectToRoute('employe_liste');
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>

    <body>

    <div class="container">
        {% block body %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    </body>
</html>

templates/projet/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des employes{% endblock %}

{% block body %}

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Prenom</th>
      <th scope="col">Nom</th>
      <th scope="col">Telephone</th>
      <th scope="col">email</th>
      <th scope="col">adresse</th>
      <th scope="col">poste</th>
      <th scope="col">salaire</th>
      <th scope="col">date de naissance</th>
    </tr>
  </thead>
  <tbody>
{% for employe in employes %} 
    <tr>
      <td >{{ employe.id }}</th>
      <td>{{ employe.prenom }}</td>
      <td>{{ employe.nom }}</td>
      <td>{{ employe.telephone }}</td>
      <td>{{ employe.email }}</td>
      <td>{{ employe.adresse }}</td>
      <td>{{ employe.poste }}</td>
      <td>{{ employe.salaire }} €</td>
      <td>{{ employe.datenaissance|date('d/m/Y') }}</td>
      <td><a href="{{path('employe_edit', {id: employe.id})}}" class="btn btn-primary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
</svg></a></td>
      <td><a onclick="return confirm('Voulez-vous supprimer cet employe ?')" href="{{path('employe_delete', {id: employe.id})}}" class="btn btn-danger"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
</svg></a></td>
    </tr>
{% endfor %}
  </tbody>
</table>


<div class="container-fluid">
  {{ form_start(form, {
      attr: {
          novalidate: 'novalidate',
      }
  }) }}
<div class="row">
  <div class="col-md-4">
    {{ form_row(form._prenom) }}
  </div>
  <div class="col-md-4">
    {{ form_row(form._nom) }}
  </div>
  <div class="col-md-4">
    {{ form_row(form._telephone) }}
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    {{ form_row(form._email) }}
  </div>
  <div class="col-md-4">
    {{ form_row(form._adresse) }}
  </div>
  <div class="col-md-4">
    {{ form_row(form._poste) }}
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    {{ form_row(form._salaire) }}
  </div>
  <div class="col-md-4">
    {{ form_row(form._datenaissance,{
        label: "Date de naissance",
        format: "d/m/YYYY"
    }) }}
  </div>
  <div class="col-md-4">
    <button type="submit" class="btn btn-success mt-2">
    {% if editMode %}
        Enrigistrer les modifications
    {% else %}
        Ajouter l'employé
    {% endif %}
    </button>
  </div>
</div>
{{ form_end(form) }}
</div>

{% endblock %}